[project]
name = "lyst"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "platformdirs>=4.5.1",
    "textual>=7.5.0",
]

[project.scripts]
lyst = "main:main"
